require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventMembershipsController do

  # This should return the minimal set of attributes required to create a valid
  # EventMembership. As you add validations to EventMembership, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventMembershipsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all event_memberships as @event_memberships" do
      event_membership = EventMembership.create! valid_attributes
      get :index, {}, valid_session
      assigns(:event_memberships).should eq([event_membership])
    end
  end

  describe "GET show" do
    it "assigns the requested event_membership as @event_membership" do
      event_membership = EventMembership.create! valid_attributes
      get :show, {:id => event_membership.to_param}, valid_session
      assigns(:event_membership).should eq(event_membership)
    end
  end

  describe "GET new" do
    it "assigns a new event_membership as @event_membership" do
      get :new, {}, valid_session
      assigns(:event_membership).should be_a_new(EventMembership)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_membership as @event_membership" do
      event_membership = EventMembership.create! valid_attributes
      get :edit, {:id => event_membership.to_param}, valid_session
      assigns(:event_membership).should eq(event_membership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventMembership" do
        expect {
          post :create, {:event_membership => valid_attributes}, valid_session
        }.to change(EventMembership, :count).by(1)
      end

      it "assigns a newly created event_membership as @event_membership" do
        post :create, {:event_membership => valid_attributes}, valid_session
        assigns(:event_membership).should be_a(EventMembership)
        assigns(:event_membership).should be_persisted
      end

      it "redirects to the created event_membership" do
        post :create, {:event_membership => valid_attributes}, valid_session
        response.should redirect_to(EventMembership.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_membership as @event_membership" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventMembership.any_instance.stub(:save).and_return(false)
        post :create, {:event_membership => {}}, valid_session
        assigns(:event_membership).should be_a_new(EventMembership)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventMembership.any_instance.stub(:save).and_return(false)
        post :create, {:event_membership => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_membership" do
        event_membership = EventMembership.create! valid_attributes
        # Assuming there are no other event_memberships in the database, this
        # specifies that the EventMembership created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventMembership.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => event_membership.to_param, :event_membership => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested event_membership as @event_membership" do
        event_membership = EventMembership.create! valid_attributes
        put :update, {:id => event_membership.to_param, :event_membership => valid_attributes}, valid_session
        assigns(:event_membership).should eq(event_membership)
      end

      it "redirects to the event_membership" do
        event_membership = EventMembership.create! valid_attributes
        put :update, {:id => event_membership.to_param, :event_membership => valid_attributes}, valid_session
        response.should redirect_to(event_membership)
      end
    end

    describe "with invalid params" do
      it "assigns the event_membership as @event_membership" do
        event_membership = EventMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_membership.to_param, :event_membership => {}}, valid_session
        assigns(:event_membership).should eq(event_membership)
      end

      it "re-renders the 'edit' template" do
        event_membership = EventMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_membership.to_param, :event_membership => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_membership" do
      event_membership = EventMembership.create! valid_attributes
      expect {
        delete :destroy, {:id => event_membership.to_param}, valid_session
      }.to change(EventMembership, :count).by(-1)
    end

    it "redirects to the event_memberships list" do
      event_membership = EventMembership.create! valid_attributes
      delete :destroy, {:id => event_membership.to_param}, valid_session
      response.should redirect_to(event_memberships_url)
    end
  end

end
